EXTRA_CFLAGS += -Ibcmdrivers/drivers/include/bcm963xx -Ibcmdrivers/shared/include/bcm963xx -Ibcmdrivers/drivers/net/enet/shared

obj-$(CONFIG_BCM_ENET_NO_RDP) += bcmenet_4908_clean.o
obj-$(CONFIG_BCM_ENET_NO_RDP) += bcmgmac_4908.o
obj-$(CONFIG_BCM_ENET_NO_RDP) += ../shared/bcmenet_ethtool.o

