# Makefile for platform init code
#

EXTRA_CFLAGS += -Ibcmdrivers/drivers/include/bcm963xx -Ibcmdrivers/shared/include/bcm963xx -Ibcmdrivers/shared/include/pmc

obj-$(CONFIG_BCM_MAP_LEGACY) += bcm_legacy_io_map.o
obj-$(CONFIG_BCM_USB) += bcm_usb.o

