# Makefile for stubs of bcm963xx board drivers
#

EXTRA_CFLAGS += -Ibcmdrivers/drivers/include/bcm963xx -Ibcmdrivers/shared/include/bcm963xx

obj-$(CONFIG_BCM_FUNC_STUBS) += boardapi-stub.o util-stub.o plat-stub.o


