EXTRA_CFLAGS += -Ibcmdrivers/drivers/include/bcm963xx -Ibcmdrivers/shared/include/bcm963xx -Ibcmdrivers/drivers/net/enet/shared

obj-$(CONFIG_BCM_PKTDMA) += bcmPktDmaEthIudma.o
obj-$(CONFIG_BCM_PKTDMA) += bcmPktDmaBds.o