obj-y += shared/boardparms/bcm963xx/
obj-y += shared/pmc/
obj-y += drivers/stubs/
obj-y += drivers/plat-bcm/
obj-y += drivers/bus/pci/host/
obj-y += drivers/net/lib/pktdma/
obj-y += drivers/net/enet/impl5/

